parameters:
  OSPlatform: ''
  pool: ''
  runUnitTests: true

stages:
- stage: ${{ parameters.OSPlatform }}Tests
  displayName: Execute ${{ parameters.OSPlatform }} Tests
  dependsOn: BuildDrawingLibraries
  pool: ${{ parameters.pool }}
  jobs:
  - ${{ if eq(parameters.runUnitTests, false) }}:
    - job: SkipUnitTest
      steps:
      - checkout: none
      - script: echo "Skip Unit tests"
  - ${{ if eq(parameters.runUnitTests, true) }}:
    - ${{ if eq(parameters.OSPlatform, 'Windows') }}:
      # Windows .NET 48 x86 Tests
      - template: ../job_templates/test_drawing_libraries.yml
        parameters:
          name: UnitTest${{ parameters.OSPlatform }}net48x86
          OSPlatform: ${{ parameters.OSPlatform }}
          framework: 'net48'
          architecture: '.x86'
          buildConfiguration: $(Configuration)
      # Windows .NET 48 x64 Tests
      - template: ../job_templates/test_drawing_libraries.yml
        parameters:
          name: UnitTest${{ parameters.OSPlatform }}net48x64
          OSPlatform: ${{ parameters.OSPlatform }}
          framework: 'net48'
          architecture: ''
          buildConfiguration: $(Configuration)
    # .NET 8.0 Tests
    - template: ../job_templates/test_drawing_libraries.yml
      parameters:
        name: UnitTest${{ parameters.OSPlatform }}net80
        OSPlatform: ${{ parameters.OSPlatform }}
        framework: 'net80'
        architecture: ''
        buildConfiguration: $(Configuration)
