parameters:
  NuGetVersion: ''
  gitHubRelease: false
  preRelease: true

jobs:
  - job: DeployDrawingLibraries
    steps:
    - checkout: none
    - task: DownloadSecureFile@1
      displayName: Download IronBarCode Code-Signing Cert
      name: DownloadSigningCert
      inputs:
        secureFile: 'ironcert.pfx'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingAssemblies'
        targetPath: 'bin/$(Configuration)'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'IronDrawingNuGet'
        targetPath: 'NuGet'
    - template: ../step_templates/sign_drawing_libraries_dll.yml
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 6.2.1
    - task: NuGetCommand@2
      displayName: 'Build DrawingLibraries NuGet Package'
      inputs:
        command: 'pack'
        packagesToPack: 'NuGet\IronSoftware.Drawing.nuspec'
        configuration: $(Configuration)
        buildProperties: 'version=${{ parameters.NuGetVersion }};IncludeSymbols=true;SymbolPackageFormat=snupkg'
        includeSymbols: true
    # Sign NuGet Packages
    - task: NuGetCommand@2
      displayName: Sign IronDrawing NuGet Package
      inputs:
        command: 'custom'
        arguments: >-
          sign $(Build.ArtifactStagingDirectory)\IronSoftware.System.Drawing.${{ parameters.NuGetVersion }}.symbols.nupkg
          -CertificatePath $(Agent.TempDirectory)\ironcert.pfx
          -Timestamper http://timestamp.digicert.com -NonInteractive -CertificatePassword $(CertificatePassword)
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'ac7dfa01-e357-472b-9830-d5cd55e71bdd/5aac0020-09d2-4b2e-a77e-47f173a1ffd6'
        includeSymbols: true
    - task: PublishSymbols@2
      inputs:
        SearchPattern: '**/*.pdb'
        indexSources: true
        publishSymbols: true
        symbolServerType: TeamServices
        detailedLog: true
    # Store Version Information
    - task: file-creator@6
      displayName: Store Version Information
      inputs:
        filepath: 'VersionInformation/versions.xml'
        filecontent: |
          <?xml version="1.0" encoding="utf-8"?>
          <Versions>
          <Configuration>$(Configuration)</Configuration>
          <IronDrawingNuGetVersion>$(NuGetVersion)</IronDrawingNuGetVersion>
          <IronDrawingAssemblyVersion>$(AssemblyVersion)</IronDrawingAssemblyVersion>
          <GitCommitHash>$(Build.SourceVersion)</GitCommitHash>
          </Versions>
        fileoverwrite: true
        verbose: true
    - task: PublishBuildArtifacts@1
      displayName: Publish IronDrawing Version Information
      inputs:
        PathtoPublish: 'VersionInformation'
        ArtifactName: 'IronDrawingVersions'
        publishLocation: 'Container'
    # Tag
    - task: PowerShell@2
      displayName: 'Display NuGet Version'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "##vso[build.addbuildtag]${{ parameters.NuGetVersion }}"'

    # Create GitHub Release with version tag
    - task: GitHubRelease@1
      condition: and(succeeded(), eq('${{ parameters.gitHubRelease }}', true), eq('${{ parameters.preRelease }}', false))
      inputs:
        isPreRelease: true
        gitHubConnection: 'ironsoftwarebuild'
        repositoryName: 'iron-software/IronSoftware.System.Drawing'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'userSpecifiedTag'
        tag: '$(NugetVersion)'
        title: 'IronSoftware.System.Drawing v$(NugetVersion)'
        releaseNotesSource: 'inline'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'